//===------------------------------------------------------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
// Also available under a BSD-style license. See LICENSE.
//
//===----------------------------------------------------------------------===//
//
// This file is automatically generated.  Please do not edit.
// Generated via:
// ```
// python -m torch_mlir.dialects.torch.importer.jit_ir.build_tools.torch_ods_gen
// ```
//
//===----------------------------------------------------------------------===//

#include "torch-mlir/Dialect/Torch/IR/TorchOps.h"

#include "UtilsForGeneratedTorchOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Support/LLVM.h"
#include "torch-mlir/Dialect/Torch/Utils/Utils.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/Support/Casting.h"

using namespace mlir;
using namespace mlir::torch;
using namespace mlir::torch::Torch;

#define GET_OP_CLASSES
#include "torch-mlir/Dialect/Torch/IR/TorchOps.cpp.inc"

// clang-format off

ParseResult AtenTanhOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenTanhOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenTanh_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenTanh_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenHardtanhOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenHardtanhOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenHardtanh_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenHardtanh_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenReluOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenReluOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenRelu_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenRelu_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenLeakyReluOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenLeakyReluOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenLeakyRelu_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenLeakyRelu_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenLogOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenLogOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenLog_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenLog_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenSigmoidOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenSigmoidOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenSigmoid_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenSigmoid_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenHardsigmoidOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenHardsigmoidOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenHardsigmoid_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenHardsigmoid_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenHardswishOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenHardswishOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenHardswish_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenHardswish_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenErfOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenErfOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenErf_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenErf_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenSiluOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenSiluOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenSilu_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenSilu_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenSinOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenSinOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenSin_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenSin_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenExpOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenExpOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenExp_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenExp_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenCosOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenCosOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenCos_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenCos_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenNegOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenNegOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenNeg_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenNeg_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenFloorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenFloorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenFloor_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenFloor_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenCeilOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenCeilOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenCeil_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenCeil_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenBitwiseNotOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenBitwiseNotOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenBitwiseNot_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenBitwiseNot_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenAddTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenAddTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenAdd_TensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenAdd_TensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenSubTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenSubTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenSub_TensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenSub_TensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenMulTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenMulTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenMul_TensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenMul_TensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenDivTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenDivTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenDiv_TensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenDiv_TensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenLerpTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenLerpTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenLerp_TensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenLerp_TensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenEqTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenEqTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenEq_TensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenEq_TensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenGtTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenGtTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenGt_TensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenGt_TensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenLtTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenLtTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenLt_TensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenLt_TensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenNeTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenNeTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenNe_TensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenNe_TensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenAddScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenAddScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenAdd_ScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenAdd_ScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenSubScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenSubScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenSub_ScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenSub_ScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenMulScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenMulScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenMul_ScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenMul_ScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenDivScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenDivScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenDiv_ScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenDiv_ScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenNeScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenNeScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenNe_ScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenNe_ScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenEqScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenEqScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenEq_ScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenEq_ScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenGtScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenGtScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenGt_ScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenGt_ScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenGeScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenGeScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenGe_ScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenGe_ScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenLtScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenLtScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenLt_ScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenLt_ScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenLeScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenLeScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenLe_ScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenLe_ScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenFmodScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenFmodScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenFmod_ScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenFmod_ScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenMaskedFillScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenMaskedFillScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenMaskedFill_ScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenMaskedFill_ScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenClampOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenClampOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenClamp_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenClamp_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenLog2Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenLog2Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenLog2_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenLog2_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenRsqrtOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenRsqrtOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenRsqrt_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenRsqrt_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenAbsOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenAbsOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenAbs_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenAbs_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenReciprocalOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenReciprocalOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenReciprocal_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenReciprocal_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenBitwiseAndTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenBitwiseAndTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenBitwiseAnd_TensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenBitwiseAnd_TensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenThresholdOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenThresholdOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenThreshold_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenThreshold_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenSquareOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenSquareOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenSquare_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenSquare_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenAddcmulOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void AtenAddcmulOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}

ParseResult AtenAddcdivOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void AtenAddcdivOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}

ParseResult AtenMaximumOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenMaximumOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenMinimumOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenMinimumOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenRsubScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenRsubScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenGeluOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenGeluOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenPowTensorScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenPowTensorScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenThresholdBackwardOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenThresholdBackwardOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenFill_ScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenFill_ScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenUniform_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void AtenUniform_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}

ParseResult AtenRandLikeOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 6, 1);
}

void AtenRandLikeOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 6, 1);
}

ParseResult AtenBernoulliOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenBernoulliOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenBernoulli_FloatOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenBernoulli_FloatOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenBernoulli_TensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenBernoulli_TensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenTriuOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenTriuOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenTriu_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenTriu_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenIndexPutOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void AtenIndexPutOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}

ParseResult AtenIndexPut_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void AtenIndexPut_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}

ParseResult AtenLinearOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenLinearOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenMmOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenMmOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenAddmmOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 5, 1);
}

void AtenAddmmOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 5, 1);
}

ParseResult AtenMatmulOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenMatmulOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenConv2dOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 7, 1);
}

void AtenConv2dOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 7, 1);
}

ParseResult AtenNativeBatchNormOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 8, 3);
}

void AtenNativeBatchNormOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 8, 3);
}

ParseResult AtenBatchNormOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 9, 1);
}

void AtenBatchNormOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 9, 1);
}

ParseResult AtenLayerNormOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 6, 1);
}

void AtenLayerNormOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 6, 1);
}

ParseResult AtenNativeLayerNormOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 5, 3);
}

void AtenNativeLayerNormOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 5, 3);
}

ParseResult AtenMaxPool2dOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 6, 1);
}

void AtenMaxPool2dOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 6, 1);
}

ParseResult AtenSoftmaxIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenSoftmaxIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenLogSoftmaxIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenLogSoftmaxIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult Aten_LogSoftmaxOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void Aten_LogSoftmaxOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenAdaptiveAvgPool2dOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenAdaptiveAvgPool2dOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenTopkOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 5, 2);
}

void AtenTopkOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 5, 2);
}

ParseResult AtenTransposeIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenTransposeIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenPermuteOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenPermuteOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenBmmOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenBmmOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenCumsumOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenCumsumOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenFloorDivideScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenFloorDivideScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenLogsumexpOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenLogsumexpOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenMeanDimOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void AtenMeanDimOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}

ParseResult Aten__And__TensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void Aten__And__TensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenSqrtOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenSqrtOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult Aten_SoftmaxOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void Aten_SoftmaxOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenMeanOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenMeanOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenStdOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenStdOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenVarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenVarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenNllLossForwardOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 5, 2);
}

void AtenNllLossForwardOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 5, 2);
}

ParseResult AtenNllLossBackwardOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 7, 1);
}

void AtenNllLossBackwardOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 7, 1);
}

ParseResult AtenBincountOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenBincountOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenConstantPadNdOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenConstantPadNdOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenSqueezeDimOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenSqueezeDimOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenUnsqueezeOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenUnsqueezeOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenSqueezeOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenSqueezeOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenFlattenUsingIntsOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenFlattenUsingIntsOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenDimOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenDimOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenSizeOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenSizeOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenBoolTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenBoolTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenOnesOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 5, 1);
}

void AtenOnesOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 5, 1);
}

ParseResult AtenNewOnesOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 6, 1);
}

void AtenNewOnesOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 6, 1);
}

ParseResult AtenZerosOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 5, 1);
}

void AtenZerosOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 5, 1);
}

ParseResult AtenNewZerosOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 6, 1);
}

void AtenNewZerosOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 6, 1);
}

ParseResult AtenTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void AtenTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}

ParseResult AtenTensorBoolOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void AtenTensorBoolOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}

ParseResult AtenTensorIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void AtenTensorIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}

ParseResult Aten_ShapeAsTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void Aten_ShapeAsTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenAllOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenAllOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenAnyOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenAnyOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenAnyDimOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenAnyDimOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenArangeOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 5, 1);
}

void AtenArangeOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 5, 1);
}

ParseResult AtenArangeStartOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 6, 1);
}

void AtenArangeStartOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 6, 1);
}

ParseResult AtenArangeStartStepOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 7, 1);
}

void AtenArangeStartStepOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 7, 1);
}

ParseResult AtenArgmaxOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenArgmaxOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenBucketizeTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void AtenBucketizeTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}

ParseResult AtenCloneOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenCloneOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenContiguousOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenContiguousOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenCopy_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenCopy_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenDetachOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenDetachOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenEmbeddingOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 5, 1);
}

void AtenEmbeddingOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 5, 1);
}

ParseResult AtenEmptyLikeOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 6, 1);
}

void AtenEmptyLikeOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 6, 1);
}

ParseResult AtenZerosLikeOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 6, 1);
}

void AtenZerosLikeOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 6, 1);
}

ParseResult AtenOnesLikeOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 6, 1);
}

void AtenOnesLikeOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 6, 1);
}

ParseResult AtenEmptyMemoryFormatOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 6, 1);
}

void AtenEmptyMemoryFormatOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 6, 1);
}

ParseResult AtenExpandOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenExpandOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenExpandAsOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenExpandAsOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenBroadcastToOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenBroadcastToOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenIndexTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenIndexTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenIndexSelectOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenIndexSelectOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult Aten_IndexPutImpl_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 5, 1);
}

void Aten_IndexPutImpl_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 5, 1);
}

ParseResult AtenItemOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenItemOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenMaskedSelectOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenMaskedSelectOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenNumelOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenNumelOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenRepeatOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenRepeatOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenReshapeOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenReshapeOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenResize_Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenResize_Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenSelectIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenSelectIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenSizeIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenSizeIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenStackOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenStackOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenSumOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenSumOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenSumDimIntListOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void AtenSumDimIntListOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}

ParseResult AtenMaxOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenMaxOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenMaxDimOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 2);
}

void AtenMaxDimOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 2);
}

ParseResult AtenToDtypeOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 5, 1);
}

void AtenToDtypeOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 5, 1);
}

ParseResult AtenToOtherOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 5, 1);
}

void AtenToOtherOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 5, 1);
}

ParseResult AtenToPrimDeviceOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 5, 1);
}

void AtenToPrimDeviceOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 5, 1);
}

ParseResult AtenTypeAsOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenTypeAsOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenViewOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenViewOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult Aten_UnsafeViewOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void Aten_UnsafeViewOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenWhereSelfOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenWhereSelfOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenSliceTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 5, 1);
}

void AtenSliceTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 5, 1);
}

ParseResult AtenLenTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenLenTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenCpuOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenCpuOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenGatherOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void AtenGatherOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}

ParseResult AtenIntImplicitOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenIntImplicitOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenTensorFloatOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void AtenTensorFloatOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}

ParseResult AtenIntTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenIntTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenFloatTensorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenFloatTensorOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenDropoutOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenDropoutOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenTOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenTOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenFullOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 6, 1);
}

void AtenFullOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 6, 1);
}

ParseResult AtenFullLikeOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 7, 1);
}

void AtenFullLikeOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 7, 1);
}

ParseResult Aten__Contains__StrOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void Aten__Contains__StrOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult Aten__Getitem__DictStrOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void Aten__Getitem__DictStrOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult Aten_SetItemStrOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 0);
}

void Aten_SetItemStrOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 0);
}

ParseResult AtenKeysStrOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenKeysStrOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenGetDefaultStrOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenGetDefaultStrOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenDeleteDictStrOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 0);
}

void AtenDeleteDictStrOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 0);
}

ParseResult AtenCatOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenCatOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenAppendTOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenAppendTOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenAddTOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenAddTOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenEqIntListOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenEqIntListOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenListTOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenListTOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenSliceTOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void AtenSliceTOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}

ParseResult AtenInsertTOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 0);
}

void AtenInsertTOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 0);
}

ParseResult AtenNeIntListOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenNeIntListOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenAddStrOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenAddStrOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenEqStrOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenEqStrOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenStrOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenStrOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenJoinOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenJoinOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenFloatScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenFloatScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenFloatStrOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenFloatStrOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenIntFloatOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenIntFloatOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult Aten__RangeLengthOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void Aten__RangeLengthOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult Aten__DeriveIndexOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void Aten__DeriveIndexOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenGtIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenGtIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenGeIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenGeIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenLtIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenLtIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenLeIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenLeIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenNeIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenNeIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenEqIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenEqIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenFloordivIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenFloordivIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenRemainderIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenRemainderIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenAddIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenAddIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenSubIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenSubIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenMulIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenMulIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenNegIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenNegIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenLogIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenLogIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenAddFloatIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenAddFloatIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenMulFloatOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenMulFloatOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenNegFloatOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenNegFloatOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenEqFloatOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenEqFloatOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenGtFloatOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenGtFloatOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenLtFloatOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenLtFloatOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenLtFloatIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenLtFloatIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult Aten__And__BoolOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void Aten__And__BoolOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenNeBoolOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenNeBoolOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult Aten__Is__Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void Aten__Is__Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult Aten__Isnot__Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void Aten__Isnot__Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult Aten__Not__Op::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void Aten__Not__Op::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult AtenLenTOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void AtenLenTOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult Aten__Getitem__TOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void Aten__Getitem__TOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult Aten_SetItemTOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void Aten_SetItemTOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult AtenDivOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenDivOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenEqDeviceOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenEqDeviceOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult Aten_SoftmaxBackwardDataOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void Aten_SoftmaxBackwardDataOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}

ParseResult AtenTanhBackwardOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void AtenTanhBackwardOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult AtenGeluBackwardOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 3, 1);
}

void AtenGeluBackwardOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 3, 1);
}

ParseResult Aten_LogSoftmaxBackwardDataOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void Aten_LogSoftmaxBackwardDataOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}

ParseResult PrimLayoutOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void PrimLayoutOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult PrimTupleIndexOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void PrimTupleIndexOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult PrimDeviceOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void PrimDeviceOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult PrimDtypeOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void PrimDtypeOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult PrimNumToTensorScalarOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void PrimNumToTensorScalarOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult PrimMinSelfIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void PrimMinSelfIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult PrimMinIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void PrimMinIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult PrimMaxSelfIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void PrimMaxSelfIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult PrimMaxIntOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 1);
}

void PrimMaxIntOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 1);
}

ParseResult PrimRaiseExceptionOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 2, 0);
}

void PrimRaiseExceptionOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 2, 0);
}

ParseResult PrimUninitializedOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 0, 1);
}

void PrimUninitializedOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 0, 1);
}

ParseResult PrimUncheckedCastOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 1, 1);
}

void PrimUncheckedCastOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 1, 1);
}

ParseResult QuantizedLinearOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseDefaultTorchOp(parser, result, 4, 1);
}

void QuantizedLinearOp::print(OpAsmPrinter &printer) {
  printDefaultTorchOp(printer, *this, 4, 1);
}
